# Generated by Django 5.2.8 on 2025-11-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=215, null=True)),
                ('descriptions', models.TextField(blank=True, max_length=215, null=True)),
                ('unit', models.TextField(blank=True, max_length=215, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('costprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sellprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('productpicture', models.TextField(blank=True, max_length=215, null=True)),
                ('alertstocks', models.IntegerField(default=0)),
                ('criticalstocks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
