# Generated by Django 5.2.8 on 2025-11-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=215, null=True)),
                ('lastname', models.CharField(blank=True, max_length=215, null=True)),
                ('email', models.CharField(max_length=215)),
                ('mobile', models.CharField(blank=True, max_length=215, null=True)),
                ('username', models.CharField(max_length=215)),
                ('password', models.CharField(max_length=215)),
                ('roles', models.CharField(max_length=215, null=True)),
                ('userpic', models.CharField(blank=True, max_length=215, null=True)),
                ('secret', models.CharField(blank=True, max_length=215, null=True)),
                ('qrcodeurl', models.CharField(blank=True, max_length=215, null=True)),
                ('isblocked', models.BooleanField(default=False)),
                ('isactivated', models.BooleanField(default=False)),
                ('mailtoken', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
